apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: infra
  namespace: flux-system
spec:
  interval: "5m"
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infra
  prune: true
  validation: client
