apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  annotations:
    metadata.weave.works/description: This is the Weave GitOps Dashboard.  It provides
      a simple way to get insights into your GitOps workloads.
  name: gitops-dash
  namespace: flux-system
spec:
  chart:
    spec:
      chart: weave-gitops
      sourceRef:
        kind: HelmRepository
        name: weaveworks
        namespace: flux-system
  interval: 1h0m0s
  values:
    adminUser:
      create: true
      passwordHash: $2a$10$STzy0F5F2uN5zsPOIIq6sODMU2eoC5AQwXyn6wzHo/m0aRVPziZoW
      username: admin
