apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
spec:
  releaseName: metrics-server
  chart:
    spec:
      chart: metrics-server
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: "*"
  interval: "1h"
  install:
    remediation:
      retries: 3
  # default values
