apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
spec:
  releaseName: prometheus
  chart:
    spec:
      chart: prometheus
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: flux-system
      version: "*"
  interval: "1h"
  install:
    remediation:
      retries: 3
  values:
    server:
      global:
        scrape_interval: 30s
      persistentVolume:
        storageClass: longhorn
      statefulSet:
        enabled: true
      retention: "168h"
    alertmanager:
      persistentVolume:
        storageClass: longhorn
      statefulSet:
        enabled: true
    networkPolicy:
      enabled: true
