apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
spec:
  releaseName: grafana
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: "*"
  interval: "1h"
  install:
    remediation:
      retries: 3
  values:
    persistence:
      enabled: true
      type: statefulset
    plugins:
      - grafana-piechart-panel
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default
    dashboards:
      default:
        cluster-monitoring-for-kubernetes:
          url: https://raw.githubusercontent.com/valerauko/flux-playground/main/infra/grafana/dashboard.json
          datasource: Prometheus
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            url: http://prometheus-server.prometheus.svc
            isDefault: true
          - name: Loki
            type: loki
            url: http://loki:3100
