apiVersion: v1
data:
  address: aHR0cHM6Ly9ncmFmYW5hLmdyYWZhbmEuc3ZjLmNsdXN0ZXIubG9jYWw=
  token: Z2xzYV9UcmRmZExJTGxySHNKRlJSb2c2b2ZoclZEbGdGeFdtUF9kNjIxM2E1YQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: flux-token
  namespace: grafana
